# Generated by Django 3.2.5 on 2021-09-02 02:13

import crud_problems_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Create_Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('question', models.CharField(max_length=50)),
                ('correct_option', models.CharField(max_length=50)),
                ('distractor1', models.CharField(max_length=50)),
                ('distractor2', models.CharField(max_length=50)),
                ('distractor3', models.CharField(max_length=50)),
                ('explanation', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to=crud_problems_app.models.user_directory_path)),
                ('abstraction', models.BooleanField()),
                ('decomposition', models.BooleanField()),
                ('algorithms', models.BooleanField()),
                ('generalization', models.BooleanField()),
                ('evaluation', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
