# Generated by Django 3.2.5 on 2021-09-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_problems_app', '0002_alter_user_create_problem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_create_problem',
            name='abstraction',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_create_problem',
            name='algorithms',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_create_problem',
            name='decomposition',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_create_problem',
            name='evaluation',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_create_problem',
            name='generalization',
            field=models.BooleanField(blank=True),
        ),
    ]
