# Generated by Django 3.2.5 on 2021-09-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_problems_app', '0003_auto_20210903_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_create_problem',
            name='explanation',
            field=models.CharField(max_length=250),
        ),
    ]
