# Generated by Django 3.2.5 on 2021-09-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_problems_app', '0010_alter_user_create_problem_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_create_problem',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
