# Generated by Django 3.2.5 on 2021-09-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_skills',
            name='abstraction',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='my_skills',
            name='algorithms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='my_skills',
            name='decomposition',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='my_skills',
            name='evaluation',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='my_skills',
            name='generalization',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='my_skills',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
