# Generated by Django 3.2.5 on 2021-09-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0002_auto_20210909_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_skills',
            name='attempts',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
