# Generated by Django 3.2.5 on 2021-09-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0003_my_skills_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_skills',
            name='correct_answers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
