# Generated by Django 3.2.5 on 2021-08-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email_user', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=40)),
                ('birthday_date', models.DateField()),
                ('access_code', models.CharField(max_length=10)),
                ('user_role', models.BooleanField()),
            ],
        ),
    ]
